use cactvs_bd;

insert into filme(titulo, ano, premio, ator, idioma, diretor, genero, produtora, sinopse, onde_assistir, nota, classificacao, foto, ativo)
values("Alita - Anjo de Combate", "2019", "Nenhum", "Rosa Salazar, Christoph Waltz & Jennifer Connelly", "Inglês", "Robert Rodriguez", "Animação", "20th Century Fox", "Uma ciborgue é descoberta por um cientista. Ela não tem memórias de sua criação, mas possui grande conhecimento de artes marciais. Enquanto busca informações sobre seu passado, trabalha como caçadora de recompensas e descobre um interesse amoroso.", "Telecine Play", "60%", "14", "Alita - Anjo de Combate.jpg", true);

insert into filme(titulo, ano, premio, ator, idioma, diretor, genero, produtora, sinopse, onde_assistir, nota, classificacao, foto, ativo)
values("Projeta Brasil - Ultraje", "2019", "Nenhum", "Roger Rocha Moreira, Edgard Scandurra, Carlo Bartolini & Leospa", "Português", "Marc Dourdin", "Documentário", "Elo Company", "Uma das bandas mais reconhecidas do cenário musical brasileiro das últimas décadas, o Ultraje a Rigor invadiu os rádios e TVs na década de 1980. No fim da Ditadura Militar a banda estava por toda parte no dia a dia dos brasileiros. É assim que começa a trajetória do grupo, que tem sua carreira e a vida de seus membros, especialmente o líder, Roger, expostas nesse documentário.", "Looke", "40%", "12", "Projeta Brasil - Ultraje.jpg", true);

insert into filme(titulo, ano, premio, ator, idioma, diretor, genero, produtora, sinopse, onde_assistir, nota, classificacao, foto, ativo)
values("Malévola – Dona do Mal", "2019", "Nenhum", "Angelina Jolie", "Inglês", "Joachim Rønning", "Aventura", "Disney", "Cinco anos após Aurora (Elle Fanning) despertar do sono profundo, a agora rainha dos Moors é pedida em casamento pelo príncipe Phillip (Harris Dickinson). Ela aceita o pedido e, com isso, parte rumo ao reino de Ulstead ao lado de Malévola (Angelina Jolie), no intuito de conhecer seus futuros sogros, John (Robert Lindsay) e Ingrith (Michelle Pfeiffer). O jantar entre eles deveria ser de celebração entre os reinos, mas os interesses de Ingrith vêm à tona quando é criado um atrito com Malévola e os demais seres mágicos.", "Disney +", "40%", "10", "Malévola – Dona do Mal.jpg", true);

insert into filme(titulo, ano, premio, ator, idioma, diretor, genero, produtora, sinopse, onde_assistir, nota, classificacao, foto, ativo)
values("A Família Addams", "2019", "Nenhum", "Charlize Theron", "Inglês", "Conrad Vernon & Greg Tiernan", "Animação", "Universal Pictures", "Para ir de mal a pior, a Família Addams precisa se preparar para receber uma visita de parentes ainda mais arrepiantes. Mas a misteriosa mansão deles parece estar com os dias de maldade contados. O clã assustador mais querido dos cinemas está de volta nessa animação baseada nos quadrinhos de Charles Addams.", "Telecine Play", "43%", "L", "Familia Addams.jpg", true);

insert into filme(titulo, ano, premio, ator, idioma, diretor, genero, produtora, sinopse, onde_assistir, nota, classificacao, foto, ativo)
values("Homem-Aranha no Aranhaverso", "2018", "Oscar Melhor Animação 2019", "Shameik Moore, Jake Johnson (XVI), Hailee Steinfeld", "Inglês", "Bob Persichetti, Peter Ramsey", "Animação", "Sony Pictures", "Miles Morales é um jovem negro do Brooklyn que se tornou o Homem-Aranha inspirado no legado de Peter Parker, já falecido. Entretanto, ao visitar o túmulo de seu ídolo em uma noite chuvosa, ele é surpreendido com a presença do próprio Peter, vestindo o traje do herói aracnídeo sob um sobretudo. A surpresa fica ainda maior quando Miles descobre que ele veio de uma dimensão paralela, assim como outras versões do Homem-Aranha.", "Disney +", "97%", "10", "Homem-Aranha no Aranhaverso.jpg", true);

insert into filme(titulo, ano, premio, ator, idioma, diretor, genero, produtora, sinopse, onde_assistir, nota, classificacao, foto, ativo)
values("Aladdin (2019)", "2019", "Nenhum", "Will Smith", "Inglês", "Guy Ritchie", "Aventura", "Disney", "Aladdin (Mena Massoud) é um jovem ladrão que vive de pequenos roubos em Agrabah. Um dia, ele ajuda uma jovem a recuperar um valioso bracelete, sem saber que ela na verdade é a princesa Jasmine (Naomi Scott). Aladdin logo fica interessado nela, que diz ser a criada da princesa. Ao visitá-la em pleno palácio e descobrir sua identidade, ele é capturado por Jafar (Marwan Kenzari), o grão-vizir do sultanato, que deseja que ele recupere uma lâmpada mágica, onde habita um gênio (Will Smith) capaz de conceder três desejos ao seu dono.", "Disney +", "57%", "10", "Aladdin (2019).jpg", true);

insert into filme(titulo, ano, premio, ator, idioma, diretor, genero, produtora, sinopse, onde_assistir, nota, classificacao, foto, ativo)
values("John Wick 3 - Parabellum", "2019", "Melhor Trailer de 2019", "Keanu Reeves", "Inglês", "Chad Stahelski", "Ação", "Paris Filmes", "Após assassinar o chefe da máfia Santino D'Antonio (Riccardo Scamarcio) no Hotel Continental, John Wick (Keanu Reeves) passa a ser perseguido pelos membros da Alta Cúpula sob a recompensa de U$14 milhões. Agora, ele precisa unir forças com antigos parceiros que o ajudaram no passado enquanto luta por sua sobrevivência.", "Netflix", "90%", "16", "John Wick 3 - Parabellum.jpg", true);

insert into filme(titulo, ano, premio, ator, idioma, diretor, genero, produtora, sinopse, onde_assistir, nota, classificacao, foto, ativo)
values("Corra!", "2017", "Oscar Melhor Roteiro Original 2018", "Daniel Kaluuya", "Inglês", "Jordan Peele", "Suspense", "Universal Pictures", "Um jovem fotográfo descobre um segredo sombrio quando conhece os pais aparentemente amigaveis de sua namorada.", "Telecine Play", "98%", "14", "Corra!.jpg", true);